services:
  - type: web
    name: entregable2-bienes-raices
    runtime: dotnet
    plan: free
    repo: https://github.com/jeanfv09/Entregable2_VilchezGuardia_JF
    branch: deploy/render
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet ./out/Entregable2_VilchezGuardia_JF.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
